#!/usr/bin/env bash
# Provision a two-region Amazon Aurora DSQL cluster (us-east-1 + us-east-2, witness us-west-2)
# and write the regional endpoints to .env.dsql (gitignored).
#
# Prereqs: AWS CLI v2 (>= 2.27.14 for the multi-region flow) and authenticated AWS creds
# (run `aws sso login` or `aws configure` first). Run from the repo root:
#
#   ./scripts/provision/provision-dsql.sh
#
# Commands verified against the AWS DSQL multi-region CLI docs (2026). Multi-region peering is
# logical: each cluster lists the other's ARN under multiRegionProperties.clusters and they
# share one witness region. There is no separate peer/link subcommand.
set -euo pipefail
export PATH="/opt/homebrew/bin:$PATH"

REGION_A="${REGION_A:-us-east-1}"
REGION_B="${REGION_B:-us-east-2}"
WITNESS="${WITNESS:-us-west-2}"
ENV_OUT="${1:-.env.dsql}"

command -v aws >/dev/null 2>&1 || { echo "ERROR: aws CLI not found (brew install awscli)"; exit 1; }
aws sts get-caller-identity >/dev/null 2>&1 || {
  echo "ERROR: not authenticated to AWS. Run:  aws sso login   (or: aws configure)"; exit 1; }
if [ -f "$ENV_OUT" ]; then
  echo "ERROR: $ENV_OUT already exists. Remove it first so this does not create orphan clusters."; exit 1
fi

ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
echo "Account $ACCOUNT. Creating multi-region DSQL: $REGION_A + $REGION_B, witness $WITNESS."

echo "1/4 create cluster in $REGION_A ..."
A_OUT="$(aws dsql create-cluster --region "$REGION_A" \
  --multi-region-properties "{\"witnessRegion\":\"$WITNESS\"}" \
  --query '[identifier,arn]' --output text)"
A_ID="$(printf '%s' "$A_OUT" | awk '{print $1}')"
A_ARN="$(printf '%s' "$A_OUT" | awk '{print $2}')"
echo "    $REGION_A id=$A_ID"

echo "2/4 create cluster in $REGION_B ..."
B_OUT="$(aws dsql create-cluster --region "$REGION_B" \
  --multi-region-properties "{\"witnessRegion\":\"$WITNESS\"}" \
  --query '[identifier,arn]' --output text)"
B_ID="$(printf '%s' "$B_OUT" | awk '{print $1}')"
B_ARN="$(printf '%s' "$B_OUT" | awk '{print $2}')"
echo "    $REGION_B id=$B_ID"

echo "3/4 peer the two clusters (each lists the other's ARN) ..."
aws dsql update-cluster --region "$REGION_A" --identifier "$A_ID" \
  --multi-region-properties "{\"witnessRegion\":\"$WITNESS\",\"clusters\":[\"$B_ARN\"]}" >/dev/null
aws dsql update-cluster --region "$REGION_B" --identifier "$B_ID" \
  --multi-region-properties "{\"witnessRegion\":\"$WITNESS\",\"clusters\":[\"$A_ARN\"]}" >/dev/null

wait_active() {
  local region="$1" id="$2" status tries=0
  while :; do
    status="$(aws dsql get-cluster --region "$region" --identifier "$id" --query status --output text 2>/dev/null || echo UNKNOWN)"
    if [ "$status" = "ACTIVE" ]; then echo "    $region $id ACTIVE"; return 0; fi
    tries=$((tries + 1))
    if [ "$tries" -gt 90 ]; then echo "    TIMEOUT waiting for $region $id (last status: $status)"; return 1; fi
    echo "    $region $id: $status (waiting, $((tries * 10))s) ..."; sleep 10
  done
}
echo "4/4 wait for ACTIVE (peering usually settles in a few minutes) ..."
wait_active "$REGION_A" "$A_ID"
wait_active "$REGION_B" "$B_ID"

A_HOST="$A_ID.dsql.$REGION_A.on.aws"
B_HOST="$B_ID.dsql.$REGION_B.on.aws"

cat > "$ENV_OUT" <<EOF
# Generated by scripts/provision/provision-dsql.sh. Gitignored (.env.*). Never commit.
# Local migrate/seed/dev use your DEFAULT AWS credential chain. Do NOT set AWS_ROLE_ARN here;
# it is only for the Vercel OIDC runtime. Keep your AWS profile active in the shell.
DSQL_ENDPOINT_EAST=$A_HOST
DSQL_ENDPOINT_WEST=$B_HOST
DSQL_DATABASE=postgres
DSQL_USER=admin
AWS_REGION=$REGION_A
EOF

echo
echo "Provisioned. Wrote $ENV_OUT:"
echo "  EAST ($REGION_A): $A_HOST"
echo "  WEST ($REGION_B): $B_HOST"
echo "  account $ACCOUNT   ARNs:"
echo "    $A_ARN"
echo "    $B_ARN"
echo
echo "Next (local, no Vercel needed):"
echo "  set -a && source $ENV_OUT && set +a   # plus: export AWS_PROFILE=<your-profile>"
echo "  pnpm migrate && pnpm seed && pnpm test:integration"
